# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -name: step 1 chek main branch from github
    - uses: actions/checkout@v2
    
    - name: step2 Set up JDK 1.2
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#         distribution: 'adopt'
    - name: step3 Build with Maven
      run: mvn -B package --file pom.xml
      
      -name: step 4 list current directory
      run: ls -a
      
      -name: step 5 target folder 
      run: |
      cd target
      ls -a
